export const journey = [
  { place: 'Pakistan', label: '01 / THE FOUNDATIONS', title: 'A willingness\nto begin.', body: 'Born and educated in Pakistan, Mohammed Rizwan took on small jobs and everyday responsibilities. Those early experiences shaped a lasting respect for honest work, practical thinking and earning trust.', note: 'Resilience. Resourcefulness. Responsibility.', position: [69, 30] },
  { place: 'Qatar', label: '02 / A WIDER WORLD', title: 'Opportunity\nbeyond home.', body: 'An employment opportunity took him to Qatar. Working across cultures strengthened his independence and broadened his understanding of people, markets and opportunity—preparing him for a larger transition.', note: 'A new country. A broader perspective.', position: [51, 25] },
  { place: 'United States', label: '03 / BUILDING A LIFE', title: 'Starting again.\nMoving forward.', body: 'More than three decades in the United States began with patience, adaptability and the courage to explore unfamiliar opportunities. In the automotive industry, he learned the work from the inside: vehicles, repairs, auctions, rentals and sales.', note: '30+ years of life and enterprise in America.', position: [-84, 34] },
];
export const ventures = [
  { name: 'Cars Compound', category: 'AUTO BODY REPAIR', short: 'The turning point', number: '01', body: 'An auto body shop in Marietta became his defining entrepreneurial turning point. Cars Compound built a foundation in vehicle repair, customer care and operational management—and the confidence to expand.', connection: 'Understanding the vehicle. Earning the customer’s trust.', x: 23, y: 24 },
  { name: 'Priceless Car Rental', category: 'RENTAL OPERATIONS', short: 'Making mobility accessible', number: '02', body: 'Acquiring a Priceless Car Rental franchise brought first-hand experience in fleet management, pricing, bookings and customer expectations. It revealed the everyday challenges faced by both renters and rental operators.', connection: 'From repairing vehicles to keeping people moving.', x: 75, y: 21 },
  { name: 'VIP Kars', category: 'AUTOMOTIVE DEALERSHIP', short: 'Confidence in every decision', number: '03', body: 'He later established VIP Kars, extending his work into vehicle sales. Sourcing, auctions, inventory and purchasing decisions added another dimension to his understanding of mobility and customer confidence.', connection: 'Connecting the right vehicle with the right person.', x: 86, y: 62 },
  { name: 'Automotive & Parts', category: 'SERVICES & JUNKYARD OPERATIONS', short: 'Knowing the whole system', number: '04', body: 'Repair services, vehicle auctions, parts and junkyard operations brought an end-to-end perspective. This wider operational experience made it possible to understand the automotive industry through more than a single business model.', connection: 'A working knowledge of the entire vehicle lifecycle.', x: 22, y: 72 },
  { name: 'Tourism & Travel', category: 'TRAVEL & MOBILITY', short: 'Looking beyond borders', number: '05', body: 'Involvement in tourism and international travel exhibitions expanded his outlook beyond local operations. It highlighted the need for easier, more connected mobility services for travellers around the world.', connection: 'Local experience meets international opportunity.', x: 56, y: 88 },
  { name: 'YalaRide', category: 'TECHNOLOGY & MOBILITY', short: 'Where experience converges', number: '06', body: 'YalaRide brings vehicles, rental operations, customer service, tourism and technology into one car-rental marketplace. Developed over approximately eighteen months, it is designed to connect renters with rental businesses and a wider choice of vehicles.', connection: 'Decades of practical knowledge. One global vision.', x: 51, y: 8 },
];
export const values = [
  ['Stay close to the work.', 'Accountability', 'He still attends vehicle auctions, monitors operations and steps in personally when a customer has a concern. Leadership begins with taking responsibility.'],
  ['Trust is earned, daily.', 'Customer trust & service', 'Listening carefully, honouring commitments and solving real problems are the foundations of a lasting business. Its value is measured by how effectively it helps people.'],
  ['Keep learning. Keep building.', 'Hard work & adaptability', 'Each country, market and venture has offered new lessons. Consistent effort and a willingness to adapt continue to shape how he leads.'],
  ['Make innovation useful.', 'Practical innovation', 'Technology should respond to everyday needs. YalaRide carries that principle into mobility: better connections, easier choices and practical value.'],
];
