export const journeyScenes = [
  { id: 'pakistan', number: '01', country: 'Pakistan', title: 'Where the story began.', copy: 'Born and educated in Pakistan, Mohammed Rizwan learned early that no honest work is too small. Different jobs and responsibilities formed the foundations of resilience, trust and ambition.', image: '/cinematic/pakistan.webp', alt: 'Badshahi Mosque in Lahore, an editorial view of Pakistan', note: 'EARLY FOUNDATIONS', credit: 'MuhammadYassal / CC BY-SA 4.0' },
  { id: 'qatar', number: '02', country: 'Qatar', title: 'A wider perspective.', copy: 'An employment opportunity took him to Qatar. Living and working away from home strengthened his independence and opened a new perspective on people, markets and opportunity.', image: '/cinematic/qatar.webp', alt: 'The Doha skyline, an editorial view of Qatar', note: 'FIRST INTERNATIONAL CHAPTER', credit: 'Thameur Belghith / CC BY-SA 4.0' },
  { id: 'united-states', number: '03', country: 'United States', title: 'The courage to begin again.', copy: 'More than three decades in the United States. A new country, a new industry and the determination to build from the ground up — one opportunity at a time.', image: '/cinematic/united-states.webp', alt: 'Statue of Liberty, an editorial view of the United States', note: 'A NEW BEGINNING', credit: 'Ypsilonatshared / Public domain' },
] as const;

export const businessChapters = [
  { id: 'cars-compound', number: '01', title: ['Cars', 'Compound'], category: 'AUTO BODY & REPAIR', location: 'MARIETTA, USA', image: '/brands/compound-project.jpg', alt: 'Automotive workshop visual supplied with Cars Compound materials', style: 'workshop', lead: 'Where hands-on work became a foundation.', copy: 'Cars Compound was Mohammed Rizwan’s major entrepreneurial turning point. Building the auto body shop gave him a foundation in vehicle repair, customer care and operational management.', role: 'Built Cars Compound as his first major entrepreneurial turning point.', highlights: ['Vehicle repair & customer care', 'A foundation for future businesses'], detail: 'Learning the realities of a competitive local market meant earning trust through the work itself. Cars Compound became the foundation for the automotive ventures that followed.', url: 'https://carscompound.com/', signature: ['Built on trust.', 'Proven through work.'] },
  { id: 'priceless', number: '02', title: ['Priceless', 'Car Rental'], category: 'CAR RENTAL OPERATIONS', location: 'MARIETTA, USA', image: '/brands/priceless-project.jpg', alt: 'White sedan on the highway with Atlanta skyline for Priceless Car Rental', style: 'workshop', lead: 'Understanding the road from both sides.', copy: 'Acquiring a Priceless Car Rental franchise expanded his work into rental operations — fleets, pricing, bookings and the everyday needs of people on the move.', role: 'Acquired a Priceless Car Rental franchise.', highlights: ['Fleet management & bookings', 'First-hand rental industry experience'], detail: 'Operating a rental business brought the challenges of customers and rental providers into sharp focus. This practical experience would later help shape the idea behind YalaRide.', url: 'https://pricelessga.com/', signature: ['More than a ride.', 'A better journey.'] },
  { id: 'vip-kars', number: '03', title: ['VIP', 'Kars'], category: 'VEHICLE SALES & DEALERSHIP', location: 'MARIETTA, USA', image: '/brands/vip-project.jpg', alt: 'VIP Kars related automotive storefront in Marietta, United States', style: 'workshop', lead: 'Another perspective on the automotive world.', copy: 'He later established VIP Kars, extending his automotive portfolio into vehicle sales. The dealership deepened his understanding of sourcing, inventory and purchasing decisions.', role: 'Established VIP Kars as an automotive dealership.', highlights: ['Vehicle sourcing & inventory', 'Customer confidence'], detail: 'Vehicle sales added another essential layer of the automotive ecosystem. Understanding what makes people confident in a major purchase became part of a broader customer-led approach.', url: 'https://www.vipkars.com/', signature: ['Drive a', 'higher standard.'] },
  { id: 'only-cash-for-cars', number: '04', title: ['Only Cash', 'for Cars USA'], category: 'VEHICLE BUYING & CASH OFFERS', location: 'MARIETTA, USA', image: '/brands/only-cash-for-cars.jpg', alt: 'Salvage yard and tow truck scene for Only Cash for Cars USA', style: 'workshop', lead: 'A direct path from seller to settlement.', copy: 'Only Cash for Cars USA reflects a practical approach to vehicle acquisition — clear offers, straightforward process and a focus on people who need a fast, reliable way to sell.', role: 'Built around cash-based vehicle buying in the United States.', highlights: ['Cash offers for vehicles', 'A faster path for sellers'], detail: 'This venture sits within his wider automotive experience: understanding cars, customers and the operational discipline required to close deals with clarity and trust.', url: 'https://onlycashforcars.com/', signature: ['Clear offers.', 'Honest process.'] },
  { id: 'lost-mountain-parts', number: '05', title: ['Lost Mountain', 'Parts LLC'], category: 'AUTO PARTS & SUPPLY', location: 'MARIETTA, USA', image: '/brands/lost-mountain-parts.jpg', alt: 'Lost Mountain Auto Parts storefront in Marietta, United States', style: 'workshop', lead: 'Keeping vehicles moving with the right parts.', copy: 'Lost Mountain Parts LLC extends his work deeper into the automotive supply chain — sourcing and supplying the components that keep repair shops and operators running.', role: 'Parts supply connected to real workshop demand.', highlights: ['Parts sourcing & supply', 'Support for repair operations'], detail: 'Parts knowledge strengthens every other automotive chapter: repair, resale and customer care all depend on getting the right component to the right place.', url: 'https://lostmountainparts.com/', signature: ['The right part.', 'At the right time.'] },
  { id: 'go-jetter', number: '06', title: ['Go-Jetter', 'Travel & Tours'], category: 'TRAVEL & TOURS · DUBAI', location: 'DUBAI', image: '/brands/go-jetter-dubai.jpg', alt: 'Dubai skyline with Burj Khalifa for Go-Jetter Travel & Tours Dubai', style: 'travel', lead: 'Hospitality with an international outlook.', copy: 'Go-Jetter Travel & Tours Dubai expands the story beyond vehicles into curated travel — connecting people to destinations, experiences and the logistics that make a journey feel effortless.', role: 'Travel and tours operations based in Dubai.', highlights: ['Destination experiences', 'International travel services'], detail: 'Working in travel sharpened his understanding of mobility from the traveller’s side — planning, timing and the expectation that every detail should feel considered.', url: 'https://go-jetter.com/', signature: ['Explore.', 'Arrive ready.'] },
  { id: 'ihawa-travel', number: '07', title: ['Ihawa Travel', 'LLC'], category: 'TRAVEL SERVICES · USA', location: 'USA', image: '/brands/ihawa-travel.jpg', alt: 'Dubai coastline aerial view for Ihawa Travel LLC', style: 'travel', lead: 'Travel support closer to home.', copy: 'Ihawa Travel LLC brings travel services into the United States chapter of his work — helping people plan movement with the same operational care he applies across his other businesses.', role: 'US-based travel services.', highlights: ['Travel planning & support', 'Customer-first service'], detail: 'Each travel venture reinforces a simple idea: mobility is not only about cars. It is about people reaching where they need to go with confidence.', url: 'https://ihawatravel.com/', signature: ['Plan well.', 'Travel better.'] },
] as const;
