export const journeyScenes = [
  { id: 'pakistan', number: '01', country: 'Pakistan', title: 'Where the story began.', copy: 'Born and educated in Pakistan, Mohammed Rizwan learned early that no honest work is too small. Different jobs and responsibilities formed the foundations of resilience, trust and ambition.', image: '/cinematic/pakistan.webp', alt: 'Badshahi Mosque in Lahore, an editorial view of Pakistan', note: 'EARLY FOUNDATIONS', credit: 'MuhammadYassal / CC BY-SA 4.0' },
  { id: 'qatar', number: '02', country: 'Qatar', title: 'A wider perspective.', copy: 'An employment opportunity took him to Qatar. Living and working away from home strengthened his independence and opened a new perspective on people, markets and opportunity.', image: '/cinematic/qatar.webp', alt: 'The Doha skyline, an editorial view of Qatar', note: 'FIRST INTERNATIONAL CHAPTER', credit: 'Thameur Belghith / CC BY-SA 4.0' },
  { id: 'united-states', number: '03', country: 'United States', title: 'The courage to begin again.', copy: 'More than three decades in the United States. A new country, a new industry and the determination to build from the ground up — one opportunity at a time.', image: '/cinematic/united-states.webp', alt: 'Statue of Liberty, an editorial view of the United States', note: 'A NEW BEGINNING', credit: 'Ypsilonatshared / Public domain' },
] as const;

export const businessChapters = [
  { id: 'cars-compound', number: '01', title: ['Cars', 'Compound'], category: 'AUTO BODY & REPAIR', location: 'MARIETTA, UNITED STATES', image: '/brands/compound-project.jpg', alt: 'Automotive workshop visual supplied with Cars Compound materials', style: 'workshop', lead: 'Where hands-on work became a foundation.', copy: 'Cars Compound was Mohammed Rizwan’s major entrepreneurial turning point. Building the auto body shop gave him a foundation in vehicle repair, customer care and operational management.', role: 'Built Cars Compound as his first major entrepreneurial turning point.', highlights: ['Vehicle repair & customer care', 'A foundation for future businesses'], detail: 'Learning the realities of a competitive local market meant earning trust through the work itself. Cars Compound became the foundation for the automotive ventures that followed.', url: 'https://carscompound.com/', signature: ['Built on trust.', 'Proven through work.'] },
  { id: 'priceless', number: '02', title: ['Priceless', 'Car Rental'], category: 'CAR RENTAL OPERATIONS', location: 'FROM SERVICE TO MOBILITY', image: '/brands/priceless-project.png', alt: 'White sedan on the highway at sunset, representing Priceless Car Rental', style: 'workshop', lead: 'Understanding the road from both sides.', copy: 'Acquiring a Priceless Car Rental franchise expanded his work into rental operations — fleets, pricing, bookings and the everyday needs of people on the move.', role: 'Acquired a Priceless Car Rental franchise.', highlights: ['Fleet management & bookings', 'First-hand rental industry experience'], detail: 'Operating a rental business brought the challenges of customers and rental providers into sharp focus. This practical experience would later help shape the idea behind YalaRide.', url: 'https://pricelesscarrental.com/', signature: ['More than a ride.', 'A better journey.'] },
  { id: 'vip-kars', number: '03', title: ['VIP', 'Kars'], category: 'VEHICLE SALES & DEALERSHIP', location: 'CONFIDENCE IN EVERY DECISION', image: '/brands/vip-project.png', alt: 'VIP Kars dealership lot and customer handover at sunset', style: 'workshop', lead: 'Another perspective on the automotive world.', copy: 'He later established VIP Kars, extending his automotive portfolio into vehicle sales. The dealership deepened his understanding of sourcing, inventory and purchasing decisions.', role: 'Established VIP Kars as an automotive dealership.', highlights: ['Vehicle sourcing & inventory', 'Customer confidence'], detail: 'Vehicle sales added another essential layer of the automotive ecosystem. Understanding what makes people confident in a major purchase became part of a broader customer-led approach.', url: 'https://www.vipkars.com/', signature: ['Drive a', 'higher standard.'] },
  { id: 'automotive', number: '04', title: ['Automotive', 'Operations'], category: 'SERVICES · AUCTIONS · JUNKYARDS', location: 'THE INDUSTRY, FROM THE INSIDE', image: '/brands/automotive-project.jpg', alt: 'Hands-on automotive work from the supplied business materials', style: 'workshop', lead: 'An understanding that runs deeper.', copy: 'Repair services, auctions, parts and junkyard operations. His broader experience spans the full automotive ecosystem, with direct involvement in the details of the work.', role: 'Hands-on involvement across connected automotive operations.', highlights: ['Vehicle auctions & parts', 'End-to-end industry understanding'], detail: 'He continues to attend vehicle auctions, monitor operations and respond personally when a customer has a concern. The perspective comes from working inside the business, rather than observing it from a distance.', signature: ['Every detail.', 'Every day.'] },
  { id: 'tourism', number: '05', title: ['Tourism'], category: 'TRAVEL & MOBILITY', location: 'A BROADER HORIZON', image: '/cinematic/tourism.webp', alt: 'A tropical coastline, an editorial illustration of travel and mobility', style: 'travel', lead: 'Looking beyond the familiar.', copy: 'Tourism and international travel exhibitions expanded his outlook beyond local automotive operations, revealing the need for easier, more connected mobility for travellers.', role: 'Participation in tourism and international travel exhibitions.', highlights: ['International industry engagement', 'A wider perspective on mobility'], detail: 'Dedicated exhibition counters for tourism initiatives and YalaRide created opportunities to build relationships and study global trends. The biography records a recent travel industry event in Riyadh, without a confirmed event name or date.', signature: ['Explore.', 'Experience', 'Connect.'] },
] as const;
