export const journeyScenes = [
  { id: 'pakistan', number: '01', country: 'Pakistan', title: 'Where the story began.', copy: 'Mohammed Rizwan was born in Pakistan. His parents moved to Doha, Qatar, where he completed his high school education.', image: '/cinematic/pakistan.webp', alt: 'Badshahi Mosque in Lahore, an editorial view of Pakistan', note: 'BORN IN PAKISTAN', credit: 'MuhammadYassal / CC BY-SA 4.0', route: 'PAKISTAN → DOHA' },
  { id: 'qatar', number: '02', country: 'Qatar', title: 'High school in Doha.', copy: 'After completing high school in Doha, he spent a short period in England before relocating to the United States in 1989.', image: '/cinematic/qatar.webp', alt: 'The Doha skyline, an editorial view of Qatar', note: 'EDUCATION IN DOHA', credit: 'Thameur Belghith / CC BY-SA 4.0', route: 'DOHA → ENGLAND' },
  { id: 'united-states', number: '03', country: 'United States', title: 'Education and a new chapter.', copy: 'In Miami, Florida, he graduated from Barry University. Since then, he has built his career and businesses in the United States across automotive, transportation, technology and travel.', image: '/cinematic/united-states.webp', alt: 'Statue of Liberty, an editorial view of the United States', note: 'UNITED STATES · 1989', credit: 'Ypsilonatshared / Public domain', route: 'ENGLAND → UNITED STATES' },
] as const;

export const businessChapters = [
  { id: 'vip-kars', number: '01', title: ['VIP Kars'], category: 'AUTOMOTIVE DEALERSHIP', location: 'ATLANTA, GEORGIA', image: '/brands/vipkars-new.png', alt: 'VIP Kars dealership lot and roadside sign in Atlanta, Georgia', style: 'workshop', lead: 'His first automotive dealership, operating for approximately 18 years.', copy: 'VIP Kars has sold more than 23,000 vehicles and continues to operate successfully, with strong sales and a loyal customer base.', role: 'Mohammed Rizwan’s first automotive dealership.', highlights: ['More than 23,000 vehicles sold', 'Strong sales & loyal customers'], detail: 'Operating in Atlanta, Georgia, for approximately 18 years, VIP Kars has built a successful dealership and a loyal customer base.', url: 'https://www.vipkars.com/', signature: ['18 years.', '23,000+ vehicles.'] },
  { id: 'cars-compound', number: '02', title: ['Cars', 'Compound'], category: 'AUTOMOTIVE SERVICE & REPAIR', location: 'MODERN SERVICE FACILITY', image: '/brands/compound-project.jpg', alt: 'Modern automotive service and repair facility for Cars Compound', style: 'workshop', lead: 'His second major automotive company, equipped for comprehensive vehicle care.', copy: 'Cars Compound operates as a modern service and repair facility, with a high-tech body shop, mechanical repair shop and advanced diagnostic services.', role: 'Second major automotive company, focused on complete repair and maintenance.', highlights: ['High-tech body & mechanical shops', 'Advanced diagnostics & maintenance'], detail: 'The company provides comprehensive automotive repair and maintenance using modern equipment and technology.', url: 'https://carscompound.com/', signature: ['Modern service.', 'Complete care.'] },
  { id: 'priceless', number: '03', title: ['Priceless', 'Car Rental'], category: 'FRANCHISE CAR RENTAL', location: 'OPERATING SINCE 2019', image: '/brands/priceless-project.jpg', alt: 'Rental car on the road for Priceless Car Rental', style: 'workshop', lead: 'A local franchise rental business serving customers since 2019.', copy: 'Priceless Car Rental serves the local community with a wide range of rental vehicles for customers, businesses and travelers.', role: 'Successfully operated as a franchise since 2019.', highlights: ['Vehicles for customers & businesses', 'Serving local travelers'], detail: 'As a franchise car-rental operation, Priceless provides vehicle choices for the everyday needs of its local community.', url: 'https://pricelessga.com/', signature: ['Local service.', 'Since 2019.'] },
  { id: 'go-jetter', number: '04', title: ['GoJetter'], category: 'TRAVEL & TOURISM', location: 'INTERNATIONAL MARKETS', image: '/brands/go-jetter-dubai.jpg', alt: 'International destination imagery for GoJetter travel and tourism', style: 'travel', lead: 'International travel services for customers and partner markets.', copy: 'GoJetter specializes in travel services, airline tickets, destination services and international tourism, serving customers and travel partners across multiple markets.', role: 'Travel and tourism company with an international presence.', highlights: ['Travel services & airline tickets', 'Destination services & tourism'], detail: 'GoJetter has developed an international presence across multiple customer and partner markets.', url: 'https://go-jetter.com/', signature: ['Travel wider.', 'Connect globally.'] },
  { id: 'lost-mountain-parts', number: '05', title: ['Lost Mountain', 'Auto Parts'], category: 'AUTO PARTS & SCRAP YARD', location: 'INTERNATIONAL EXPORTS', image: '/brands/lost-mountain-parts.jpg', alt: 'Used auto-parts and scrap-yard operations for Lost Mountain', style: 'workshop', lead: 'Used auto parts, vehicle dismantling and international exports.', copy: 'Lost Mountain dismantles vehicles, sells quality used auto parts, processes scrap vehicles and materials, and exports used parts internationally, including to Dubai.', role: 'Used auto-parts and scrap-yard business.', highlights: ['Vehicle dismantling & scrap processing', 'Used parts exported to Dubai'], detail: 'The business combines vehicle dismantling, used-parts sales and scrap processing with international exports.', url: 'https://lostmountainparts.com/', signature: ['Parts recovered.', 'Resources reused.'] },
  { id: 'yalaride', number: '06', title: ['YalaRide'], category: 'INTERNATIONAL CAR-RENTAL MARKETPLACE', location: 'MOROCCO · PANAMA · COSTA RICA', image: '/brands/yalaride-car.webp', alt: 'YalaRide international car-rental marketplace', style: 'technology', lead: 'A more affordable, flexible alternative to traditional global travel marketplaces.', copy: 'YalaRide.com connects customers directly with independent and franchise car-rental operators around the world.', role: 'International marketplace and technology platform.', highlights: ['Competitive commissions for operators', 'Greater control over inventory & pricing'], detail: 'The platform is being developed to support flexible pricing, insurance and protection choices, additional rental services and technology integrations. Expansion is gradual, country by country, through local partnerships and reliable customer service.', url: 'https://yalaride.com/', signature: ['Choice for renters.', 'Control for partners.'] },
  { id: 'rizitech', number: '07', title: ['RizItech'], category: 'TECHNOLOGY & DIGITAL MARKETING', location: 'AUTOMOTIVE · TRANSPORTATION', image: '/brands/rizitech-project.png', alt: 'Digital-marketing and technology studio serving automotive and transportation businesses', style: 'workshop', lead: 'Technology and digital marketing for automotive and transportation businesses.', copy: 'RizItech provides website development, SEO, digital marketing, social media management, Google advertising, AI solutions and business technology services.', role: 'Technology and marketing partner for the company group and industry clients.', highlights: ['Websites, SEO & digital advertising', 'AI, automation & social media'], detail: 'RizItech also supports the group’s automotive and travel businesses with digital infrastructure, using technology, AI, automation and marketing to attract customers and improve operations.', signature: ['Technology for', 'business growth.'] },
] as const;
